In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("quikr_car.csv")

In [3]:
df.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB

In [5]:
df['year'].unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '...', '150k', 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs',
       'sale', '1995', 'ara)', '2002', 'SELL', '2001', 'tion', 'odel',
       '2 bs', 'arry', 'Eon', 'o...', 'ture', 'emi', 'car', 'able', 'no.',
       'd...', 'SALE', 'digo', 'sell', 'd Ex', 'n...', 'e...', 'D...',
       ', Ac', 'go .', 'k...', 'o c4', 'zire', 'cent', 'Sumo', 'cab',
       't xe', 'EV2', 'r...', 'zest'], dtype=object)

In [6]:
df1 = df.copy()

In [7]:
df1['year'].value_counts()

year
2015    117
2014     94
2013     94
2016     76
2012     75
       ...
cab       1
t xe      1
EV2       1
r...      1
zest      1
Name: count, Length: 61, dtype: int64

In [8]:
# Extract only 4-digit numbers from the column
df['year'] = df['year'].str.extract(r'(\d{4})')

In [9]:
df1['year']

0      2007
1      2006
2      2018
3      2014
4      2014
       ...
887    zest
888    2018
889    2013
890    2014
891    2014
Name: year, Length: 892, dtype: object

In [10]:
# Convert to numeric
#✅ What to_numeric() does
#pd.to_numeric(..., errors='coerce') converts:
# "2007" → 2007.0
# "abcd" → NaN
# "r 15" → NaN
# "2005" → 2005.0
# So now all valid numbers become numeric (float), and junk becomes NaN.
# Then we drop NaN, and only THEN convert to int.

df1['year'] = pd.to_numeric(df1['year'], errors='coerce')

In [11]:
# keep only reasonable year range
df1['year'] = df1['year'].where(df1['year'].between(1990, 2025))

In [12]:
# Drop rows where year is missing after cleaning
df1 = df1.dropna(subset=['year'])

# Convert to int
df1['year'] = df1['year'].astype(int)

In [13]:
df['Price']

0             80,000
1           4,25,000
2      Ask For Price
3           3,25,000
4           5,75,000
           ...
887         3,10,000
888         2,60,000
889         3,90,000
890         1,80,000
891         1,60,000
Name: Price, Length: 892, dtype: object

In [14]:
df1 = df1[df1['Price'].str.contains(r'^[0-9, ]+$', na=False)]

In [15]:
df1['Price'] = df1['Price'].str.replace(',', '', regex=False).str.replace(' ', '')

In [16]:
df1['Price'] = df1['Price'].astype(int)

In [17]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 819 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        819 non-null    object
 1   company     819 non-null    object
 2   year        819 non-null    int64
 3   Price       819 non-null    int64
 4   kms_driven  819 non-null    object
 5   fuel_type   816 non-null    object
dtypes: int64(2), object(4)
memory usage: 44.8+ KB

In [18]:
df1['kms_driven']

0        45,000 kms
1            40 kms
3        28,000 kms
4        36,000 kms
6        41,000 kms
           ...
886    1,32,000 kms
888      27,000 kms
889      40,000 kms
890          Petrol
891          Petrol
Name: kms_driven, Length: 819, dtype: object

In [19]:
# 1. Remove the word 'kms' (case-insensitive)
df1['kms_driven'] = df1['kms_driven'].str.replace('kms', '', case=False, regex=False)

In [20]:
# 2. Remove commas and spaces
df1['kms_driven'] = df1['kms_driven'].str.replace(',', '', regex=False).str.replace(' ', '')

In [21]:
df1 = df1[df1['kms_driven'].str.contains(r'^\d+$', na=False)]

In [22]:
df1['kms_driven'] = df1['kms_driven'].astype(int)

In [23]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 817 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        817 non-null    object
 1   company     817 non-null    object
 2   year        817 non-null    int64
 3   Price       817 non-null    int64
 4   kms_driven  817 non-null    int64
 5   fuel_type   816 non-null    object
dtypes: int64(3), object(3)
memory usage: 44.7+ KB

In [24]:
df1 = df1.dropna(subset=['fuel_type'])

In [25]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 816 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        816 non-null    object
 1   company     816 non-null    object
 2   year        816 non-null    int64
 3   Price       816 non-null    int64
 4   kms_driven  816 non-null    int64
 5   fuel_type   816 non-null    object
dtypes: int64(3), object(3)
memory usage: 44.6+ KB

In [26]:
df1['name']

0        Hyundai Santro Xing XO eRLX Euro III
1                     Mahindra Jeep CL550 MDI
3      Hyundai Grand i10 Magna 1.2 Kappa VTVT
4            Ford EcoSport Titanium 1.5L TDCi
6                                   Ford Figo
                        ...
883                Maruti Suzuki Ritz VXI ABS
885                 Tata Indica V2 DLE BS III
886                      Toyota Corolla Altis
888                       Tata Zest XM Diesel
889                        Mahindra Quanto C8
Name: name, Length: 816, dtype: object

In [27]:
df1['name'] = df1['name'].str.split().str[:3].str.join(' ')

In [28]:
df1.head()

                     name   company  year   Price  kms_driven fuel_type
0     Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1     Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
3       Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
4  Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
6               Ford Figo      Ford  2012  175000       41000    Diesel

In [29]:
df1['Price']

0       80000
1      425000
3      325000
4      575000
6      175000
        ...
883    270000
885    110000
886    300000
888    260000
889    390000
Name: Price, Length: 816, dtype: int64

In [30]:
df1.describe()

              year         Price     kms_driven
count   816.000000  8.160000e+02     816.000000
mean   2012.444853  4.117176e+05   46275.531863
std       4.002992  4.751844e+05   34297.428044
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   27000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.912500e+05   56818.500000
max    2019.000000  8.500003e+06  400000.000000